# Generated by Django 2.2.6 on 2019-10-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191016_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PK', models.IntegerField()),
                ('FIRST_NAME', models.CharField(max_length=20)),
                ('LAST_NAME', models.CharField(max_length=20)),
            ],
        ),
    ]
