# Generated by Django 2.2.6 on 2019-10-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='PK',
        ),
    ]
